### ISSUE TITLE
Contribution to Syntax Sprint

### ISSUE THREAD

**Issue by SaeedNMosleh** [rbrickmn/syntaxsprint-app#1]
Hi Riley,

  I found this awesome project in CodeCademy. I'm learning Front-End in CodeCademy too. 
May I ask if this project is open to contribution? 
I would like to help implement new features.

Cheers,
Saeed

**Comment by rbrickmn** [comment]
Hi Saeed, that sounds great! I would love that, do you need anything to get started or are you able to get it running on your system?

**Comment by SaeedNMosleh** [comment]
Great! The code is clean and the architecture is understandable. It runs smoothly after cloning
I will submit my first PR soon which contains a tiny change.
 
Then I have a plan to work on adding the dark mode. Is it fine?
I also noticed that the Prism library has been added to the project but I didn't see syntax highlighting in the output.  Is it implemented?

**Comment by rbrickmn** [comment]
Apologies for the late response! Didn't see a notification. Thank you for your comments on the code being clean! As for Prism, I was intending on trying it out for the project, but I never got around to it once things started flowing together. We can either use it for something in the project or drop it. 

Also, I love your dark mode idea! I'd love to see your implementation :)

**Comment by SaeedNMosleh** [comment]
Thanks for the kind comments on PR and accepting it. It's my first "issue" and "PR" in GitHub :)

I will use local storage as a placeholder for a global variable for the theme and CSS variables in index.css for the dark mode.  I found this pattern here:  https://css-tricks.com/easy-dark-mode-and-multiple-color-themes-in-react/

Please feel free to close this issue and open a new item in "issues" or "projects" with related tags to follow items separately. I think it would be helpful, especially in the case of complex PRs and features.
