### ISSUE TITLE
Feature: Dark Mode Implementation

### ISSUE THREAD

**Issue by rbrickmn** [rbrickmn/syntaxsprint-app#3]
Hello all, this is the issue page for the dark theme feature! I can't wait to see where this goes.

**Comment by bryanguillen** [comment]
Hello! I can help out if needed.

**Comment by rbrickmn** [comment]
Totally! Welcome :) I just opened this one up actually.

**Comment by bryanguillen** [comment]
Nice! Looks like a fun project and I would love to help out.

Quick question: Do you have a slack or discord channel for chatting?

**Comment by Oscur007** [comment]
I could've helped but by the time someone might have helped you already . If not , then I would like to give a try . Good luck by the way .

**Comment by rbrickmn** [comment]
Go ahead and give it a spin! This is a fresh issue so contribution is welcome

**Comment by bryanguillen** [comment]
@rbrickmn , how does contributing work? Do you assign someone or allow as many PRs to income and choose whichever one is the best fit?

**Comment by rbrickmn** [comment]
Hi! Sorry for the late reply. I'm new to collaborating so let's just try allowing multiple PR's and the best fit will be merged!

**Comment by rbrickmn** [comment]
I'll also go ahead and assign both of you due to your interest!

**Comment by bryanguillen** [comment]
@rbrickmn , that's okay. You can assign it @Oscur007 . I'd rather be assigned a task that's assigned to just me, this way I avoid spending time on something that will not be merged. I'm thinking, is there something else you could use help with? Looks like a fun project, so let me know.

**Comment by SaeedNMosleh** [comment]
Thanks! My PR is almost ready from the functional point but I'm struggling with colors. I'm not good at design :)
I noticed an additional branch has been created, Can I still submit my PR for the main branch?

**Comment by rbrickmn** [comment]
@SaeedNMosleh I like these ideas a lot actually! I was thinking about a leaderboard not too long ago - could be an excellent addition! Syntax highlighting also could be great. Also to answer your question about the branch, yes you can submit it! Go ahead, I was just testing things out with making branches.

**Comment by SaeedNMosleh** [comment]
The PR for dark mode is submitted. Hope it works fine :)

We can discuss the leaderboard in a separate thread. It may require a small API to save/load list. I will explore possible options.

**Comment by rbrickmn** [comment]
Thank you so much for your contribution, Saeed! Your PR has been approved & merged, every line of code is making this app even better!

**Comment by SaeedNMosleh** [comment]
Thank you for your encouraging words and positive energy! Looking forward to contributing more to future features :)
